-- Aivana: postgres schema
--
-- run once against your database:
--   psql "postgresql://USER:PASSWORD@HOST:5432/DBNAME" -f schema.sql
--
-- safe to run again: every statement uses IF NOT EXISTS.
-- table and index names match db.py, so the app sees these tables and
-- won't try to create them again.

BEGIN;

-- people who can log in
CREATE TABLE IF NOT EXISTS users (
    id                  VARCHAR(36)  PRIMARY KEY,               -- uuid, generated by the app
    email               VARCHAR(255) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,                  -- scrypt hash, never the password
    reply_language_mode VARCHAR(10)  NOT NULL DEFAULT 'auto'
        CHECK (reply_language_mode IN ('auto', 'match', 'fixed')),
    reply_language      VARCHAR(50)  NOT NULL DEFAULT 'English',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email);

-- each user's own provider api keys, encrypted with ENCRYPTION_KEY (fernet)
CREATE TABLE IF NOT EXISTS api_keys (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       VARCHAR(36) NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider      VARCHAR(50) NOT NULL,                         -- openai, anthropic, xai, ...
    encrypted_key TEXT        NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, provider)                                  -- one key per provider per user
);
CREATE INDEX IF NOT EXISTS ix_api_keys_user_id ON api_keys (user_id);

-- conversations
CREATE TABLE IF NOT EXISTS chats (
    id         VARCHAR(36)  PRIMARY KEY,                        -- uuid, generated by the app
    user_id    VARCHAR(36)  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title      VARCHAR(200) NOT NULL DEFAULT 'New chat',
    summary    TEXT,                                            -- 3-4 sentence summary, written after the first reply
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- for databases created before the summary column existed
ALTER TABLE chats ADD COLUMN IF NOT EXISTS summary TEXT;
CREATE INDEX IF NOT EXISTS ix_chats_user_id ON chats (user_id);
-- the sidebar lists a user's chats newest first
CREATE INDEX IF NOT EXISTS ix_chats_user_updated ON chats (user_id, updated_at DESC);

-- every message in every conversation
CREATE TABLE IF NOT EXISTS messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id    VARCHAR(36)  NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
    role       VARCHAR(10)  NOT NULL CHECK (role IN ('human', 'ai')),
    content    TEXT         NOT NULL,
    model      VARCHAR(100),                                    -- which model wrote an ai message
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_messages_chat_id ON messages (chat_id);
-- loading a chat reads its messages in order
CREATE INDEX IF NOT EXISTS ix_messages_chat_order ON messages (chat_id, id);

COMMIT;

-- ---------- documents (needs the pgvector extension) ----------

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE messages ADD COLUMN IF NOT EXISTS sources TEXT;  -- json list of cited passages

-- uploaded pdfs; the file itself lives in storage under storage_key
CREATE TABLE IF NOT EXISTS documents (
    id          VARCHAR(36)  PRIMARY KEY,
    user_id     VARCHAR(36)  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    filename    VARCHAR(255) NOT NULL,
    size_bytes  INTEGER      NOT NULL,
    sha256      VARCHAR(64)  NOT NULL,
    storage_key VARCHAR(300) NOT NULL,
    pages       INTEGER      NOT NULL DEFAULT 0,
    status      VARCHAR(12)  NOT NULL DEFAULT 'processing'
        CHECK (status IN ('processing', 'ready', 'failed')),
    progress    INTEGER      NOT NULL DEFAULT 0,
    error       TEXT,
    chunk_count INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (user_id, sha256)                                    -- the same file is stored once per user
);
CREATE INDEX IF NOT EXISTS ix_documents_user_id ON documents (user_id);

-- passages of each document with their embeddings (bge-m3, 1024 dimensions,
-- half precision to halve storage)
CREATE TABLE IF NOT EXISTS document_chunks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id VARCHAR(36)  NOT NULL REFERENCES documents (id) ON DELETE CASCADE,
    chunk_index INTEGER      NOT NULL,
    page        INTEGER      NOT NULL,                          -- 1-based page, for citations
    content     TEXT         NOT NULL,
    embedding   HALFVEC(1024)
);
CREATE INDEX IF NOT EXISTS ix_document_chunks_document_id ON document_chunks (document_id);
-- keyword search; 'simple' treats every language alike
CREATE INDEX IF NOT EXISTS ix_document_chunks_fts
    ON document_chunks USING gin (to_tsvector('simple', content));

-- which documents are attached to which chat
CREATE TABLE IF NOT EXISTS chat_documents (
    chat_id     VARCHAR(36) NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
    document_id VARCHAR(36) NOT NULL REFERENCES documents (id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (chat_id, document_id)
);

COMMIT;
